version: "3.8"

services:
  app:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: dotnet_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConnection=Host=db;Port=5432;Database=appdb;Username=postgres;Password=postgres
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:12.22
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
